name: dart_telegram_bot_api
version: 0.5.1
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  html: any
  json: any
  path: any
  mime: any
  http: 0.11.3
  dotenv: any
  events: any
  http_parser: any
