name: dart_telegram_bot_api
version: 0.6.0
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  html: any
  json: any
  path: any
  mime: any
  http: any
  dotenv: any
  events: any
  http_parser: any
  command_wrapper: any
